/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int ACHAVES = 10;
  /** RegularExpression Id. */
  int FCHAVES = 11;
  /** RegularExpression Id. */
  int APARENTESES = 12;
  /** RegularExpression Id. */
  int FPARENTESES = 13;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 14;
  /** RegularExpression Id. */
  int ATRIBUICAO = 15;
  /** RegularExpression Id. */
  int SAIDA = 16;
  /** RegularExpression Id. */
  int ENTRADA = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int DEF = 22;
  /** RegularExpression Id. */
  int SOMA = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int SUB = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int MENOR = 29;
  /** RegularExpression Id. */
  int MAIOR = 30;
  /** RegularExpression Id. */
  int IGUAL = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int VIRGULA = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"let\"",
    "\"void\"",
    "\"float\"",
    "\"bool\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":=\"",
    "\"printIO\"",
    "\"readIO\"",
    "\"if\"",
    "\"do\"",
    "\"while\"",
    "\"return\"",
    "\"def\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "<NUM>",
    "<ID>",
  };

}
